version: "3.3"
services:
  nginx-proxy:
    image: registrygw.azurecr.io/nginx-proxy:latest
    ports:
      - "443:443"
    expose:
      - "443"
    build:
      context: .
      dockerfile: Dockerfile-nginx
  auth-api:
    image: registrygw.azurecr.io/auth-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Azure
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "4042:80"
    expose:
      - "4042"
    build:
      context: .
      dockerfile: Auth.API/Dockerfile
  goblin-api:
    image: registrygw.azurecr.io/goblin-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Azure
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "4041:80"
    expose:
      - "4041"
    build:
      context: .
      dockerfile: Goblin.API/Dockerfile
  gw-background:
    image: registrygw.azurecr.io/gw-background
    environment:
      - ASPNETCORE_ENVIRONMENT=Azure
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"
    expose:
      - "5001"
    build:
      context: .
      dockerfile: GoblinWars.BackgroundService/Dockerfile
  equipments-api:
    image: registrygw.azurecr.io/equipments-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Azure
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "4043:80"
    expose:
      - "4043"
    build:
      context: .
      dockerfile: Equipment.API/Dockerfile
    depends_on:
      - "nginx-proxy"
