using System;
namespace NoChainSwap.DTO.Enum
{
    [Flags]
    public enum GenesEnum : long
    {
        RaceSkin,
        RaceHair,
        RaceEyes,
        RaceEar,
        RaceMouth,
        //Forest
        ForestSkin,
        ForestHair,
        ForestEyes,
        ForestEar,
        ForestMouth,
        //Desert
        DesertSkin,
        DesertHair,
        DesertEyes,
        DesertEar,
        DesertMouth,
        //Cave
        CaveSkin,
        CaveHair,
        CaveEyes,
        CaveEar,
        CaveMouth,
        //Dark
        DarkSkin,
        DarkHair,
        DarkEyes,
        DarkEar,
        DarkMouth,
        //Dark
        SeaSkin,
        SeaHair,
        SeaEyes,
        SeaEar,
        SeaMouth,
    }
}
