export enum EquipmentTypeEnum {
  Material = 0,
  Tool = 1,
  Helmet = 2,
  BodyArmor = 3,
  LegArmor = 4,
  HandArmor = 5,
  FootArmor = 6,
  RightHand = 7,
  LeftHand = 8,
  Sword = 9,
  Sword2Hands = 10,
  Shield = 11,
  Knife = 12,
  Staff = 13,
  Crossbow = 14,
  Hammer = 15,
  Axe = 16,
  Greataxe = 17,
  Mace = 18,
  Spear = 19,
  Bow = 20,
  Pickaxe = 21,
}